name: Greeting on variable day

on: 
  push:
    branches: [new-cli]

env: 
  Day_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubantu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env: 
          First_Name: Mona
